development:
  bucket_name: aerolaplata-dev
  access_key_id: '02V7C7ZXFM8C0Z8VTYG2'
  secret_access_key: 'nH0Pc/T4Iuotqd6R1/1LnHNPDKhjWJEl8/Qn/9Gr'

test:
  bucket_name: aerolaplata_test
  access_key_id: '02V7C7ZXFM8C0Z8VTYG2'
  secret_access_key: 'nH0Pc/T4Iuotqd6R1/1LnHNPDKhjWJEl8/Qn/9Gr'